### ISSUE TITLE
User Command

### ISSUE THREAD

**Issue by fancythedeveloper** [Wyliemaster/GDPS-Bot-Beta#1]
When trying to use the user command, it gives this.

`/home/runner/dashps-bot/commands/user.js:30
        let searchData = bodyArr[1].split(':');
                                    ^

TypeError: Cannot read property 'split' of undefined
    at Request.callback [as _callback] (/home/runner/dashps-bot/commands/user.js:30:37)
    at Request.self.callback (/home/runner/dashps-bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/runner/dashps-bot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/runner/dashps-bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)`

**Comment by fancythedeveloper** [comment]
Nevermind, fixed the link in `server` on botsettings and works now!
